### ISSUE TITLE
IMPORTANT

### ISSUE THREAD

**Issue by FlqmzeCraft** [usejxo/Furnace#1]
Can I help  create it because Im good at coding, I know all llangauges trust me. heres my proflio: https: https://guns.lol/flqmzecraft, https://flqmzecraft.netlify.app/

**Comment by FlqmzeCraft** [comment]
Want to work togather?

**Comment by usejxo** [comment]
Okay 
here's the launcher I made [Jlauncher The perfect launcher for eaglercraft](https://jlauncher.netlify.app)
also if you know how to rework the main eaglercraft ui yes
to show me what you know make a simple eaglerforge mod that opens a custom gui with 0
